---
- hosts: all  # Target all hosts in your inventory
  become: yes  # Required for privileged operations like package upgrades and reboots

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Perform a dist-upgrade
      apt:
        upgrade: dist

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes
        purge: yes

    - name: Autoclean
      apt:
        autoclean: yes

    - name: Clean
      apt:
        clean: yes

    - name: Reboot if necessary
      reboot:
        msg: "Reboot initiated by Ansible due to system updates."
      when: reboot_required_file.stat.exists
